language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --prefer-source

script: composer test

after_success:
  - if [[ "`phpenv version-name`" != "7.3" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


cache:
  directories:
    - $HOME/.composer/cache
